name: Generate Rules

permissions:
  contents: write

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  generate-rules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Cache previous remote files
        id: cache-remote
        uses: actions/cache@v3
        with:
          path: |
            old_direct.tmp
            old_proxy.tmp
            old_reject.tmp
            old_steamcn.tmp
          key: remote-files-${{ github.run_id }}
          restore-keys: remote-files-

      - name: Check for changes in custom files and remote sources
        id: check-changes
        run: |
          CUSTOM_CHANGED=false
          if [ -d custom ] && git diff --name-only HEAD^ HEAD -- custom/*.list | grep -q .; then
            CUSTOM_CHANGED=true
            echo "Custom files have changed"
          fi
          declare -A urls=(
            [direct]="https://raw.githubusercontent.com/GMOogway/shadowrocket-rules/master/sr_direct_list.module"
            [proxy]="https://raw.githubusercontent.com/GMOogway/shadowrocket-rules/master/sr_proxy_list.module"
            [reject]="https://raw.githubusercontent.com/GMOogway/shadowrocket-rules/master/sr_reject_list.module"
            [steamcn]="https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/SteamCN/SteamCN.list"
          )
          REMOTE_CHANGED=false
          for type in "${!urls[@]}"; do
            curl -s -I "${urls[$type]}" -o headers.txt
            ETAG=$(grep -i "ETag" headers.txt | cut -d'"' -f2)
            LAST_MODIFIED=$(grep -i "Last-Modified" headers.txt | cut -d' ' -f2-)
            echo "${type}_etag=$ETAG" >> $GITHUB_OUTPUT
            echo "${type}_last_modified=$LAST_MODIFIED" >> $GITHUB_OUTPUT
            if [ -f "old_${type}.tmp" ]; then
              OLD_HASH=$(sha256sum "old_${type}.tmp" | cut -d' ' -f1)
              curl -s "${urls[$type]}" -o "new_${type}.tmp"
              NEW_HASH=$(sha256sum "new_${type}.tmp" | cut -d' ' -f1)
              if [ "$OLD_HASH" != "$NEW_HASH" ]; then
                REMOTE_CHANGED=true
                echo "${urls[$type]} has changed"
              fi
              mv "new_${type}.tmp" "old_${type}.tmp"
            else
              curl -s "${urls[$type]}" -o "old_${type}.tmp"
              REMOTE_CHANGED=true
              echo "No previous ${type} file found"
            fi
          done
          if [ "$CUSTOM_CHANGED" = true ] || [ "$REMOTE_CHANGED" = true ]; then
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          else
            echo "changes_detected=false" >> $GITHUB_OUTPUT
          fi
        continue-on-error: true

      - name: Exit if no changes or check failed
        if: steps.check-changes.outputs.changes_detected != 'true'
        run: |
          if [ "${{ steps.check-changes.outcome }}" = "failure" ]; then
            echo "Change detection failed, assuming changes to be safe"
            exit 1
          else
            echo "No changes detected, skipping build"
            exit 0
          fi
      - name: Prepare folders
        run: mkdir -p shadowrocket mihomo custom

      - name: Process rules
        run: |
          declare -A urls=(
            [direct]="sr_direct_list.module"
            [proxy]="sr_proxy_list.module"
            [reject]="sr_reject_list.module"
          )
          for type in "${!urls[@]}"; do
            curl -s "https://raw.githubusercontent.com/GMOogway/shadowrocket-rules/master/${urls[$type]}" -o "temp.module"
            sed '1,/^\[Rule\]$/d' temp.module | \
              sed "s/,${type^^}$//" | \
              sed '/^IP-CIDR\|^IP-ASN\|^GEOIP/s/$/,no-resolve/' > "shadowrocket/${type}.list"
            rm temp.module
          done
          curl -s https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/SteamCN/SteamCN.list -o steamcn.list
          grep -v '^#' steamcn.list >> shadowrocket/direct.list
          sort -u shadowrocket/direct.list -o shadowrocket/direct.list
          rm steamcn.list
          for type in direct proxy reject; do
            if [ -f "custom/${type}.list" ]; then
              grep -v '^#' "custom/${type}.list" >> "shadowrocket/${type}.list"
              sort -u "shadowrocket/${type}.list" -o "shadowrocket/${type}.list"
            fi
          done
          for file in shadowrocket/*.list; do
            grep "^DOMAIN-SUFFIX," "$file" | cut -d',' -f2 | tr '[:upper:]' '[:lower:]' > suffixes.txt
            grep "^DOMAIN," "$file" | cut -d',' -f2 | tr '[:upper:]' '[:lower:]' > domains.txt
            cp "$file" temp_file.txt
            while read -r domain; do
              if grep -q "^$domain$" suffixes.txt || grep -q "^.*\.$domain$" suffixes.txt; then
                sed -i "/^DOMAIN,${domain}$/Id" temp_file.txt
              fi
            done < domains.txt
            sort -fu temp_file.txt > "$file"
            rm -f temp_file.txt suffixes.txt domains.txt
          done
          for type in direct proxy reject; do
            sed 's/^URL-REGEX/^DOMAIN-REGEX/' "shadowrocket/${type}.list" > "mihomo/${type}.list"
          done
      - name: Commit and Push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add shadowrocket/*.list mihomo/*.list
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update rule lists - $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
            git push
          fi
