name: Process Shadowrocket Rules

on:
  schedule:
    # 北京时间上午7点 (UTC时间比北京时间晚8小时，所以是23:00前一天)
    - cron: '0 23 * * *'
  workflow_dispatch: # 允许手动触发

permissions:
  contents: write  # 授予写入权限以推送更改

jobs:
  process-rules:
    runs-on: ubuntu-latest

    steps:
      # 检出代码库
      - name: Checkout repository
        uses: actions/checkout@v4

      # 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # 安装依赖，包括 requests
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # 运行 Python 脚本处理规则
      - name: Process rules
        run: |
          python .github/scripts/process_rules.py

      # 提交并推送生成的文件
      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add shadowrocket/* mihomo/*
          git commit -m "Update processed rule sets" || echo "No changes to commit"
          git push
