name: Update Shadowrocket and mihomo Rules

on:
  schedule:
    - cron: '0 23 * * *' # Runs at 23:00 UTC (7:00 Beijing Time, UTC+8)
  workflow_dispatch: # Allows manual triggering

jobs:
  update-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Cache remote files
        id: cache-remote
        uses: actions/cache@v4
        with:
          path: .github/cache
          key: ${{ runner.os }}-remote-files-${{ hashFiles('custom/*-url.list') }}

      - name: Run update script
        run: python .github/scripts/update_rules.py

      - name: Check for changes
        id: check-changes
        run: |
          if git diff --quiet; then
            echo "No changes detected, skipping commit."
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected, proceeding with commit."
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.check-changes.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add shadowrocket/*.list mihomo/*.list
          git commit -m "Update rules - $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
          git push
