name: Update Shadowrocket and Mihomo Rules

on:
  schedule:
    - cron: '0 23 * * *' # 北京时间 7:00 (UTC 23:00)
  workflow_dispatch: # 允许手动触发

jobs:
  update-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run rule generation script
        run: python .github/scripts/generate_rules.py

      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add shadowrocket/ mihomo/
          git commit -m "Update rules on $(date +'%Y-%m-%d %H:%M:%S UTC')"
          git push